version: "3.3"

services:
  api:
    build: ./
    container_name: flashlight
    restart: always
    volumes:
      - /usr/local/flashlight/upload:/data/flashlight/upload
    command: >
        sh -c "python cli.py migrate &&
               python cli.py api --host 0.0.0.0 --port 8000"
    env_file:
      - ./env/.env.main
    ports:
      - "8000:8000"
    depends_on:
      - db
    
  db:
    image: postgres
    command: ["postgres",]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    env_file:
      - ./env/.env.main
    expose:
      - "55499"
    ports:
      - "55499:5432"
    volumes:
      - /usr/local/flashlight/db:/data/postgres
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == vmAPT1
